
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module tcp_packet_receiver(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// HPS //////////
	inout 		          		HPS_CONV_USB_N,
	output		    [14:0]		HPS_DDR3_ADDR,
	output		     [2:0]		HPS_DDR3_BA,
	output		          		HPS_DDR3_CAS_N,
	output		          		HPS_DDR3_CKE,
	output		          		HPS_DDR3_CK_N,
	output		          		HPS_DDR3_CK_P,
	output		          		HPS_DDR3_CS_N,
	output		     [3:0]		HPS_DDR3_DM,
	inout 		    [31:0]		HPS_DDR3_DQ,
	inout 		     [3:0]		HPS_DDR3_DQS_N,
	inout 		     [3:0]		HPS_DDR3_DQS_P,
	output		          		HPS_DDR3_ODT,
	output		          		HPS_DDR3_RAS_N,
	output		          		HPS_DDR3_RESET_N,
	input 		          		HPS_DDR3_RZQ,
	output		          		HPS_DDR3_WE_N,
	output		          		HPS_ENET_GTX_CLK,
	inout 		          		HPS_ENET_INT_N,
	output		          		HPS_ENET_MDC,
	inout 		          		HPS_ENET_MDIO,
	input 		          		HPS_ENET_RX_CLK,
	input 		     [3:0]		HPS_ENET_RX_DATA,
	input 		          		HPS_ENET_RX_DV,
	output		     [3:0]		HPS_ENET_TX_DATA,
	output		          		HPS_ENET_TX_EN,
	inout 		     [3:0]		HPS_FLASH_DATA,
	output		          		HPS_FLASH_DCLK,
	output		          		HPS_FLASH_NCSO,
	inout 		     [1:0]		HPS_GPIO,
	inout 		          		HPS_GSENSOR_INT,
	inout 		          		HPS_I2C1_SCLK,
	inout 		          		HPS_I2C1_SDAT,
	inout 		          		HPS_I2C2_SCLK,
	inout 		          		HPS_I2C2_SDAT,
	inout 		          		HPS_I2C_CONTROL,
	inout 		          		HPS_KEY,
	inout 		          		HPS_LED,
	output		          		HPS_SD_CLK,
	inout 		          		HPS_SD_CMD,
	inout 		     [3:0]		HPS_SD_DATA,
	output		          		HPS_SPIM_CLK,
	input 		          		HPS_SPIM_MISO,
	output		          		HPS_SPIM_MOSI,
	inout 		          		HPS_SPIM_SS,
	input 		          		HPS_UART_RX,
	output		          		HPS_UART_TX,
	input 		          		HPS_USB_CLKOUT,
	inout 		     [7:0]		HPS_USB_DATA,
	input 		          		HPS_USB_DIR,
	input 		          		HPS_USB_NXT,
	output		          		HPS_USB_STP
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

    wire rst_n = KEY[0];
    wire [7:0] pkt_count;

//=======================================================
//  Structural coding
//=======================================================

    // We instantiate the specific Terasic generated Qsys structure.
    soc_system u_qsys (
        .clk_clk                 (CLOCK_50),     //     clk.clk
        .reset_reset_n           (rst_n),        //   reset.reset_n
        .pio_export_export       (pkt_count),    //  bridge output!
        
        // HPS DDR3 Memory
        .memory_mem_a            (HPS_DDR3_ADDR),
        .memory_mem_ba           (HPS_DDR3_BA),
        .memory_mem_ck           (HPS_DDR3_CK_P),
        .memory_mem_ck_n         (HPS_DDR3_CK_N),
        .memory_mem_cke          (HPS_DDR3_CKE),
        .memory_mem_cs_n         (HPS_DDR3_CS_N),
        .memory_mem_ras_n        (HPS_DDR3_RAS_N),
        .memory_mem_cas_n        (HPS_DDR3_CAS_N),
        .memory_mem_we_n         (HPS_DDR3_WE_N),
        .memory_mem_reset_n      (HPS_DDR3_RESET_N),
        .memory_mem_dq           (HPS_DDR3_DQ),
        .memory_mem_dqs          (HPS_DDR3_DQS_P),
        .memory_mem_dqs_n        (HPS_DDR3_DQS_N),
        .memory_mem_odt          (HPS_DDR3_ODT),
        .memory_mem_dm           (HPS_DDR3_DM),
        .memory_oct_rzqin        (HPS_DDR3_RZQ),
        
        // HPS Ethernet
        .hps_0_hps_io_hps_io_emac1_inst_TX_CLK (HPS_ENET_GTX_CLK),
        .hps_0_hps_io_hps_io_emac1_inst_TXD0   (HPS_ENET_TX_DATA[0]),
        .hps_0_hps_io_hps_io_emac1_inst_TXD1   (HPS_ENET_TX_DATA[1]),
        .hps_0_hps_io_hps_io_emac1_inst_TXD2   (HPS_ENET_TX_DATA[2]),
        .hps_0_hps_io_hps_io_emac1_inst_TXD3   (HPS_ENET_TX_DATA[3]),
        .hps_0_hps_io_hps_io_emac1_inst_RXD0   (HPS_ENET_RX_DATA[0]),
        .hps_0_hps_io_hps_io_emac1_inst_MDIO   (HPS_ENET_MDIO),
        .hps_0_hps_io_hps_io_emac1_inst_MDC    (HPS_ENET_MDC),
        .hps_0_hps_io_hps_io_emac1_inst_RX_CTL (HPS_ENET_RX_DV),
        .hps_0_hps_io_hps_io_emac1_inst_TX_CTL (HPS_ENET_TX_EN),
        .hps_0_hps_io_hps_io_emac1_inst_RX_CLK (HPS_ENET_RX_CLK),
        .hps_0_hps_io_hps_io_emac1_inst_RXD1   (HPS_ENET_RX_DATA[1]),
        .hps_0_hps_io_hps_io_emac1_inst_RXD2   (HPS_ENET_RX_DATA[2]),
        .hps_0_hps_io_hps_io_emac1_inst_RXD3   (HPS_ENET_RX_DATA[3]),

        // HPS QSPI
        .hps_0_hps_io_hps_io_qspi_inst_IO0     (HPS_FLASH_DATA[0]),
        .hps_0_hps_io_hps_io_qspi_inst_IO1     (HPS_FLASH_DATA[1]),
        .hps_0_hps_io_hps_io_qspi_inst_IO2     (HPS_FLASH_DATA[2]),
        .hps_0_hps_io_hps_io_qspi_inst_IO3     (HPS_FLASH_DATA[3]),
        .hps_0_hps_io_hps_io_qspi_inst_SS0     (HPS_FLASH_NCSO),
        .hps_0_hps_io_hps_io_qspi_inst_CLK     (HPS_FLASH_DCLK),

        // HPS SD Card
        .hps_0_hps_io_hps_io_sdio_inst_CMD     (HPS_SD_CMD),
        .hps_0_hps_io_hps_io_sdio_inst_D0      (HPS_SD_DATA[0]),
        .hps_0_hps_io_hps_io_sdio_inst_D1      (HPS_SD_DATA[1]),
        .hps_0_hps_io_hps_io_sdio_inst_CLK     (HPS_SD_CLK),
        .hps_0_hps_io_hps_io_sdio_inst_D2      (HPS_SD_DATA[2]),
        .hps_0_hps_io_hps_io_sdio_inst_D3      (HPS_SD_DATA[3]),

        // HPS USB
        .hps_0_hps_io_hps_io_usb1_inst_D0      (HPS_USB_DATA[0]),
        .hps_0_hps_io_hps_io_usb1_inst_D1      (HPS_USB_DATA[1]),
        .hps_0_hps_io_hps_io_usb1_inst_D2      (HPS_USB_DATA[2]),
        .hps_0_hps_io_hps_io_usb1_inst_D3      (HPS_USB_DATA[3]),
        .hps_0_hps_io_hps_io_usb1_inst_D4      (HPS_USB_DATA[4]),
        .hps_0_hps_io_hps_io_usb1_inst_D5      (HPS_USB_DATA[5]),
        .hps_0_hps_io_hps_io_usb1_inst_D6      (HPS_USB_DATA[6]),
        .hps_0_hps_io_hps_io_usb1_inst_D7      (HPS_USB_DATA[7]),
        .hps_0_hps_io_hps_io_usb1_inst_CLK     (HPS_USB_CLKOUT),
        .hps_0_hps_io_hps_io_usb1_inst_STP     (HPS_USB_STP),
        .hps_0_hps_io_hps_io_usb1_inst_DIR     (HPS_USB_DIR),
        .hps_0_hps_io_hps_io_usb1_inst_NXT     (HPS_USB_NXT),

        // HPS SPI
        .hps_0_hps_io_hps_io_spim1_inst_CLK    (HPS_SPIM_CLK),
        .hps_0_hps_io_hps_io_spim1_inst_MOSI   (HPS_SPIM_MOSI),
        .hps_0_hps_io_hps_io_spim1_inst_MISO   (HPS_SPIM_MISO),
        .hps_0_hps_io_hps_io_spim1_inst_SS0    (HPS_SPIM_SS),

        // HPS UART
        .hps_0_hps_io_hps_io_uart0_inst_RX     (HPS_UART_RX),
        .hps_0_hps_io_hps_io_uart0_inst_TX     (HPS_UART_TX),

        // HPS I2C
        .hps_0_hps_io_hps_io_i2c0_inst_SDA     (HPS_I2C1_SDAT),
        .hps_0_hps_io_hps_io_i2c0_inst_SCL     (HPS_I2C1_SCLK),
        .hps_0_hps_io_hps_io_i2c1_inst_SDA     (HPS_I2C2_SDAT),
        .hps_0_hps_io_hps_io_i2c1_inst_SCL     (HPS_I2C2_SCLK),

        // HPS GPIO
        .hps_0_hps_io_hps_io_gpio_inst_GPIO09  (HPS_CONV_USB_N),
        .hps_0_hps_io_hps_io_gpio_inst_GPIO35  (HPS_ENET_INT_N),
        .hps_0_hps_io_hps_io_gpio_inst_GPIO40  (HPS_GPIO[0]),
        .hps_0_hps_io_hps_io_gpio_inst_GPIO48  (HPS_I2C_CONTROL),
        .hps_0_hps_io_hps_io_gpio_inst_GPIO53  (HPS_LED),
        .hps_0_hps_io_hps_io_gpio_inst_GPIO54  (HPS_KEY),
        .hps_0_hps_io_hps_io_gpio_inst_GPIO61  (HPS_GSENSOR_INT)
    );

    // Turn off VGA specifically since you added it
    assign VGA_BLANK_N = 1'b1;
    assign VGA_SYNC_N  = 1'b0;
    assign VGA_CLK     = 1'b0;
    assign {VGA_B, VGA_G, VGA_R} = 24'h0;
    assign {VGA_HS, VGA_VS} = 2'b0;

    // Convert binary pkt_count back to decimal for the 7-segment displays
    reg [3:0] tens, ones;
    always @(*) begin
        tens = pkt_count / 10;
        ones = pkt_count % 10;
    end

    // Hex Decoders
    seven_seg_decoder h0 (ones, HEX0);
    seven_seg_decoder h1 (tens, HEX1);
    
    // Display "E ---"
    seven_seg_decoder h5 (4'd14, HEX5); 
    seven_seg_decoder h4 (4'd15, HEX4); // Dash
    seven_seg_decoder h3 (4'd15, HEX3); // Dash
    seven_seg_decoder h2 (4'd15, HEX2); // Dash

    // Map LEDs to switches as a basic sanity check
    assign LEDR = SW;

endmodule

// Helper Decoder
module seven_seg_decoder (
    input [3:0] code,
    output reg [6:0] segs
);
    // 0 = active ON
    always @(*) case(code)
        0: segs = 7'b1000000;
        1: segs = 7'b1111001;
        2: segs = 7'b0100100;
        3: segs = 7'b0110000;
        4: segs = 7'b0011001;
        5: segs = 7'b0010010;
        6: segs = 7'b0000010;
        7: segs = 7'b1111000;
        8: segs = 7'b0000000;
        9: segs = 7'b0010000;
        14: segs = 7'b0000110; // 'E'
        15: segs = 7'b0111111; // '-'
        default: segs = 7'b1111111; // Blank
    endcase
endmodule
