//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
import ob_pkg::*;
module ParserXOrderbook(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output	reg	     [6:0]		HEX0,
	output	reg	     [6:0]		HEX1,
	output	reg	     [6:0]		HEX2,
	output	reg	     [6:0]		HEX3,
	output	reg	     [6:0]		HEX4,
	output	reg	     [6:0]		HEX5,
	
	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW
);

localparam DATA_WIDTH = 8;
localparam DEPTH = 8;

localparam FILL = 2'd0;
localparam EXEC = 2'd1;
localparam DONE = 2'd2;

parameter HEX_0 = 7'b1000000;		// zero
parameter HEX_1 = 7'b1111001;		// one
parameter HEX_2 = 7'b0100100;		// two
parameter HEX_3 = 7'b0110000;		// three
parameter HEX_4 = 7'b0011001;		// four
parameter HEX_5 = 7'b0010010;		// five
parameter HEX_6 = 7'b0000010;		// six
parameter HEX_7 = 7'b1111000;		// seven
parameter HEX_8 = 7'b0000000;		// eight
parameter HEX_9 = 7'b0011000;		// nine
parameter HEX_10 = 7'b0001000;	// ten
parameter HEX_11 = 7'b0000011;	// eleven
parameter HEX_12 = 7'b1000110;	// twelve
parameter HEX_13 = 7'b0100001;	// thirteen
parameter HEX_14 = 7'b0000110;	// fourteen
parameter HEX_15 = 7'b0001110;	// fifteen
parameter OFF   = 7'b1111111;		// all off

logic rst_n, valid_i, valid_d, valid, o_valid;
logic new_input_i, new_input_d, new_input;
logic [PRICE_LEN-1:0] i_best_bid, i_best_ask, o_bid_price, o_ask_price, display_bid_price, display_ask_price;
logic [PRICE_LEN-1:0] best_bid1, best_bid2, best_bid3, best_bid4, best_bid5;
logic [PRICE_LEN-1:0] best_ask1, best_ask2, best_ask3, best_ask4, best_ask5;
logic [47:0] i_order_time, i_order_time1, i_order_time2, i_order_time3, i_order_time4, i_order_time5;
assign rst_n = KEY[0];
assign valid_i = KEY[1];
assign new_input_i = KEY[2];
assign valid = valid_i && (!valid_d);
assign new_input = new_input_i && (!new_input_d);


tl_top dut(
	.i_clk(CLOCK_50),
    .i_rst_n(rst_n),
    .i_best_bid(i_best_bid),
    .i_best_ask(i_best_ask),
    .i_order_time(i_order_time),
    .i_price_valid(valid),
    .i_trade_valid(1'b1),
    .i_trade_side(0),   // 0 = buy, 1 = sell
    .i_trade_qty(16'd30),

    .o_bid_price(o_bid_price),
    .o_ask_price(o_ask_price),
    .o_bid_qty(),
    .o_ask_qty(),
    // output logic                 o_order_type,// AS always quotes both sides
    .o_valid(o_valid)
);


always_ff @(posedge CLOCK_50, negedge rst_n) begin
	if(!rst_n) begin
		i_best_bid <= '0;
		i_best_ask <= '0;
		i_order_time <= '0;
		best_bid1 <= 16'd22389;
		best_bid2 <= 16'd22389;
		best_bid3 <= 16'd22389;
		best_bid4 <= 16'd22389;
		best_bid5 <= 16'd22389;
		best_ask1 <= 16'd22413;
		best_ask2 <= 16'd22410;
		best_ask3 <= 16'd22408;
		best_ask4 <= 16'd22407;
		best_ask5 <= 16'd22405;
		i_order_time1 <= 48'd3420448;
		i_order_time2 <= 48'd3420465;
		i_order_time3 <= 48'd3420510;
		i_order_time4 <= 48'd3420516;
		i_order_time5 <= 48'd3420551;
	end else if(new_input) begin
		i_best_bid <= best_bid1;
		best_bid1 <= best_bid2;
		best_bid2 <= best_bid3;
		best_bid3 <= best_bid4;
		best_bid4 <= best_bid5;
		i_best_ask <= best_ask1;
		best_ask1 <= best_ask2;
		best_ask2 <= best_ask3;
		best_ask3 <= best_ask4;
		best_ask4 <= best_ask5;
		i_order_time <= i_order_time1;
		i_order_time1 <= i_order_time2;
		i_order_time2 <= i_order_time3;
		i_order_time3 <= i_order_time4;
		i_order_time4 <= i_order_time5;
	end
end

always_ff @(posedge CLOCK_50, negedge rst_n) begin
	if(!rst_n) begin
		new_input_d <= 0;
		valid_d <= 0;
	end else begin
		new_input_d <= new_input_i;
		valid_d <= valid_i;
	end
end

always_ff @(posedge CLOCK_50, negedge rst_n) begin
	if(!rst_n) begin
		display_bid_price <= '0;
		display_ask_price <= '0;
	end else if(o_valid)begin
		display_bid_price <= o_bid_price;
		display_ask_price <= o_ask_price;
	end
end

// logic [1:0] i_action, quantity;
// logic rst_n, valid_i, valid_d, valid, o_bid_best_valid, o_ask_best_valid, o_valid;
// logic [PRICE_LEN-1:0] i_price, o_bid_best_price, o_ask_best_price, o_price;
// logic [QUANTITY_LEN-1 :0] i_quantity, o_quantity;
// logic [TOT_QUATITY_LEN-1:0] o_bid_best_quant, o_ask_best_quant;
// logic [1:0] o_action;
// logic o_side;
// logic new_input_i, new_input_d, new_input;
// logic i_side, side1, side2, side3, side4, side5, side6, side7, side8, side9, side10, side11, side12, side13, side14, side15, side16;
// logic [PRICE_LEN-1:0]price1, price2, price3, price4, price5, price6, price7, price8, price9, price10, price11, price12, price13, price14, price15, price16;
// logic [QUANTITY_LEN-1 :0] quant1, quant2, quant3, quant4, quant5, quant6, quant7, quant8, quant9, quant10, quant11, quant12, quant13, quant14, quant15, quant16;
// logic [1:0] action1, action2, action3, action4, action5, action6, action7, action8, action9, action10, action11, action12, action13, action14, action15, action16;
// logic [ORDERID_LEN-1:0] i_order_id, order_id1, order_id2, order_id3, order_id4, order_id5, order_id6, order_id7, order_id8, order_id9, order_id10, order_id11, order_id12, order_id13, order_id14, order_id15, order_id16;



// assign rst_n = KEY[0];
// assign valid_i = KEY[1];
// assign new_input_i = KEY[2];
// assign valid = valid_i && (!valid_d);
// assign new_input = new_input_i && (!new_input_d);

// always_ff @(posedge CLOCK_50, negedge rst_n) begin
// 	if(!rst_n) begin
// 		new_input_d <= 0;
// 		valid_d <= 0;
// 	end else begin
// 		new_input_d <= new_input_i;
// 		valid_d <= valid_i;
// 	end
// end

// always_ff @(posedge CLOCK_50, negedge rst_n) begin
// 	if(!rst_n) begin
// 		i_order_id <= '0;
// 		i_price <= '0;
// 		i_quantity <= '0;
// 		i_action <= '0;
// 		i_side <= 0;
// 		price1 <= 16'd22382;
// 		price2 <= 16'd22382;
// 		price3 <= 16'd22399;
// 		price4 <= 16'd22399;
// 		price5 <= 16'd22399;
// 		price6 <= 16'd22399;
// 		price7 <= 16'd22399;
// 		price8 <= 16'd22400;
// 		price9 <= 16'd22400;
// 		price10 <= 16'd22400;
// 		price11 <= 16'd22400;
// 		price12 <= 16'd22400;
// 		price13 <= 16'd22395;
// 		price14 <= 16'd22395;
// 		price15 <= 16'd22395;
// 		price16 <= 16'd22386;

// 		quant1 <= 12'd21;
// 		quant2 <= 12'd21;
// 		quant3 <= 12'd100;
// 		quant4 <= 12'd90;
// 		quant5 <= 12'd50;
// 		quant6 <= 12'd10;
// 		quant7 <= 12'd50;
// 		quant8 <= 12'd100;
// 		quant9 <= 12'd100;
// 		quant10 <= 12'd100;
// 		quant11 <= 12'd100;
// 		quant12 <= 12'd100;
// 		quant13 <= 12'd100;
// 		quant14 <= 12'd100;
// 		quant15 <= 12'd75;
// 		quant16 <= 12'd100;

// 		side1 <= 0;
// 		side2 <= 0;
// 		side3 <= 1;
// 		side4 <= 1;
// 		side5 <= 1;
// 		side6 <= 1;
// 		side7 <= 1;
// 		side8 <= 1;
// 		side9 <= 1;
// 		side10 <= 1;
// 		side11 <= 1;
// 		side12 <= 1;
// 		side13 <= 1;
// 		side14 <= 1;
// 		side15 <= 1;
// 		side16 <= 1;
		

// 		action1 <= 2'b00;
// 		action2 <= 2'b01;
// 		action3 <= 2'b00;
// 		action4 <= 2'b10;
// 		action5 <= 2'b00;
// 		action6 <= 2'b01;
// 		action7 <= 2'b01;
// 		action8 <= 2'b00;
// 		action9 <= 2'b01;
// 		action10 <= 2'b00;
// 		action11 <= 2'b01;
// 		action12 <= 2'b00;
// 		action13 <= 2'b00;
// 		action14 <= 2'b01;
// 		action15 <= 2'b00;
// 		action16 <= 2'b00;

// 		order_id1 <= 16'd0;
// 		order_id2 <= 16'd0;
// 		order_id3 <= 16'd1;
// 		order_id4 <= 16'd1;
// 		order_id5 <= 16'd2;
// 		order_id6 <= 16'd1;
// 		order_id7 <= 16'd2;
// 		order_id8 <= 16'd3;
// 		order_id9 <= 16'd3;
// 		order_id10 <= 16'd4;
// 		order_id11 <= 16'd4;
// 		order_id12 <= 16'd5;
// 		order_id13 <= 16'd6;
// 		order_id14 <= 16'd6;
// 		order_id15 <= 16'd7;
// 		order_id16 <= 16'd7;

// 	end else if(new_input)begin
// 		i_order_id <= order_id1;
// 		order_id1 <= order_id2;
// 		order_id2 <= order_id3;
// 		order_id3 <= order_id4;
// 		order_id4 <= order_id5;
// 		order_id5 <= order_id6;
// 		order_id6 <= order_id7;
// 		order_id7 <= order_id8;
// 		order_id8 <= order_id9;
// 		order_id9 <= order_id10;
// 		order_id10 <= order_id11;
// 		order_id11 <= order_id12;
// 		order_id12 <= order_id13;
// 		order_id13 <= order_id14;
// 		order_id14 <= order_id15;
// 		order_id15 <= order_id16;
// 		i_price <= price1;
// 		price1 <= price2;
// 		price2 <= price3;
// 		price3 <= price4;
// 		price4 <= price5;
// 		price5 <= price6;
// 		price6 <= price7;
// 		price7 <= price8;
// 		price8 <= price9;
// 		price9 <= price10;
// 		price10 <= price11;
// 		price11 <= price12;
// 		price12 <= price13;
// 		price13 <= price14;
// 		price14 <= price15;
// 		price15 <= price16;
// 		i_quantity <= quant1;
// 		quant1 <= quant2;
// 		quant2 <= quant3;
// 		quant3 <= quant4;
// 		quant4 <= quant5;
// 		quant5 <= quant6;
// 		quant6 <= quant7;
// 		quant7 <= quant8;
// 		quant8 <= quant9;
// 		quant9 <= quant10;
// 		quant10 <= quant11;
// 		quant11 <= quant12;
// 		quant12 <= quant13;
// 		quant13 <= quant14;
// 		quant14 <= quant15;
// 		quant15 <= quant16;
// 		i_action <= action1;
// 		action1 <= action2;
// 		action2 <= action3;
// 		action3 <= action4;
// 		action4 <= action5;
// 		action5 <= action6;
// 		action6 <= action7;
// 		action7 <= action8;
// 		action8 <= action9;
// 		action9 <= action10;
// 		action10 <= action11;
// 		action11 <= action12;
// 		action12 <= action13;
// 		action13 <= action14;
// 		action14 <= action15;
// 		action15 <= action16;
// 		i_side <= side1;
// 		side1 <= side2;
// 		side2 <= side3;
// 		side3 <= side4;
// 		side4 <= side5;
// 		side5 <= side6;
// 		side6 <= side7;
// 		side7 <= side8;
// 		side8 <= side9;
// 		side9 <= side10;
// 		side10 <= side11;
// 		side11 <= side12;
// 		side12 <= side13;
// 		side13 <= side14;
// 		side14 <= side15;
// 		side15 <= side16;
// 	end
// end


// orderbook #(.BASE_PRICE(22000))ob(
// 	.i_clk(CLOCK_50),
// 	.i_rst_n(rst_n),
// 	.i_order_id(i_order_id),
// 	.i_side(i_side),
// 	.i_price(i_price),
// 	.i_quantity(i_quantity),
// 	.i_action(i_action),
// 	.i_valid(valid),
// 	.o_bid_best_price(o_bid_best_price),
// 	.o_bid_best_quant(o_bid_best_quant),
// 	.o_ask_best_price(o_ask_best_price),
// 	.o_ask_best_quant(o_ask_best_quant),
// 	.o_bid_best_valid(o_bid_best_valid),
// 	.o_ask_best_valid(o_ask_best_valid),
// 	.o_action(o_action),
// 	.o_price(o_price),
// 	.o_quantity(o_quantity),
// 	.o_valid(o_valid),
// 	.o_side(o_side)
// );

always_comb begin
		case(display_bid_price[3:0])
			4'd0: HEX0 = HEX_0;
			4'd1: HEX0 = HEX_1;
			4'd2: HEX0 = HEX_2;
			4'd3: HEX0 = HEX_3;
			4'd4: HEX0 = HEX_4;
			4'd5: HEX0 = HEX_5;
			4'd6: HEX0 = HEX_6;
			4'd7: HEX0 = HEX_7;
			4'd8: HEX0 = HEX_8;
			4'd9: HEX0 = HEX_9;
			4'd10: HEX0 = HEX_10;
			4'd11: HEX0 = HEX_11;
			4'd12: HEX0 = HEX_12;
			4'd13: HEX0 = HEX_13;
			4'd14: HEX0 = HEX_14;
			4'd15: HEX0 = HEX_15;
		endcase
end

always_comb begin
		case(display_bid_price[7:4])
			4'd0: HEX1 = HEX_0;
			4'd1: HEX1 = HEX_1;
			4'd2: HEX1 = HEX_2;
			4'd3: HEX1 = HEX_3;
			4'd4: HEX1 = HEX_4;
			4'd5: HEX1 = HEX_5;
			4'd6: HEX1 = HEX_6;
			4'd7: HEX1 = HEX_7;
			4'd8: HEX1 = HEX_8;
			4'd9: HEX1 = HEX_9;
			4'd10: HEX1 = HEX_10;
			4'd11: HEX1 = HEX_11;
			4'd12: HEX1 = HEX_12;
			4'd13: HEX1 = HEX_13;
			4'd14: HEX1 = HEX_14;
			4'd15: HEX1 = HEX_15;
		endcase
end

always_comb begin
		case(display_bid_price[11:8])
			4'd0: HEX2 = HEX_0;
			4'd1: HEX2 = HEX_1;
			4'd2: HEX2 = HEX_2;
			4'd3: HEX2 = HEX_3;
			4'd4: HEX2 = HEX_4;
			4'd5: HEX2 = HEX_5;
			4'd6: HEX2 = HEX_6;
			4'd7: HEX2 = HEX_7;
			4'd8: HEX2 = HEX_8;
			4'd9: HEX2 = HEX_9;
			4'd10: HEX2 = HEX_10;
			4'd11: HEX2 = HEX_11;
			4'd12: HEX2 = HEX_12;
			4'd13: HEX2 = HEX_13;
			4'd14: HEX2 = HEX_14;
			4'd15: HEX2 = HEX_15;
		endcase
end

always_comb begin
		case(display_ask_price[3:0])
			4'd0: HEX3 = HEX_0;
			4'd1: HEX3 = HEX_1;
			4'd2: HEX3 = HEX_2;
			4'd3: HEX3 = HEX_3;
			4'd4: HEX3 = HEX_4;
			4'd5: HEX3 = HEX_5;
			4'd6: HEX3 = HEX_6;
			4'd7: HEX3 = HEX_7;
			4'd8: HEX3 = HEX_8;
			4'd9: HEX3 = HEX_9;
			4'd10: HEX3 = HEX_10;
			4'd11: HEX3 = HEX_11;
			4'd12: HEX3 = HEX_12;
			4'd13: HEX3 = HEX_13;
			4'd14: HEX3 = HEX_14;
			4'd15: HEX3 = HEX_15;
		endcase
end

always_comb begin
		case(display_ask_price[7:4])
			4'd0: HEX4 = HEX_0;
			4'd1: HEX4 = HEX_1;
			4'd2: HEX4 = HEX_2;
			4'd3: HEX4 = HEX_3;
			4'd4: HEX4 = HEX_4;
			4'd5: HEX4 = HEX_5;
			4'd6: HEX4 = HEX_6;
			4'd7: HEX4 = HEX_7;
			4'd8: HEX4 = HEX_8;
			4'd9: HEX4 = HEX_9;
			4'd10: HEX4 = HEX_10;
			4'd11: HEX4 = HEX_11;
			4'd12: HEX4 = HEX_12;
			4'd13: HEX4 = HEX_13;
			4'd14: HEX4 = HEX_14;
			4'd15: HEX4 = HEX_15;
		endcase
end
always_comb begin
		case(display_ask_price[11:8])
			4'd0: HEX5 = HEX_0;
			4'd1: HEX5 = HEX_1;
			4'd2: HEX5 = HEX_2;
			4'd3: HEX5 = HEX_3;
			4'd4: HEX5 = HEX_4;
			4'd5: HEX5 = HEX_5;
			4'd6: HEX5 = HEX_6;
			4'd7: HEX5 = HEX_7;
			4'd8: HEX5 = HEX_8;
			4'd9: HEX5 = HEX_9;
			4'd10: HEX5 = HEX_10;
			4'd11: HEX5 = HEX_11;
			4'd12: HEX5 = HEX_12;
			4'd13: HEX5 = HEX_13;
			4'd14: HEX5 = HEX_14;
			4'd15: HEX5 = HEX_15;
		endcase
end



endmodule