//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
import ob_pkg::*;
module ParserXOrderbook(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output	reg	     [6:0]		HEX0,
	output	reg	     [6:0]		HEX1,
	output	reg	     [6:0]		HEX2,
	output	reg	     [6:0]		HEX3,
	output	reg	     [6:0]		HEX4,
	output	reg	     [6:0]		HEX5,
	
	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW
);

localparam DATA_WIDTH = 8;
localparam DEPTH = 8;

localparam FILL = 2'd0;
localparam EXEC = 2'd1;
localparam DONE = 2'd2;

parameter HEX_0 = 7'b1000000;		// zero
parameter HEX_1 = 7'b1111001;		// one
parameter HEX_2 = 7'b0100100;		// two
parameter HEX_3 = 7'b0110000;		// three
parameter HEX_4 = 7'b0011001;		// four
parameter HEX_5 = 7'b0010010;		// five
parameter HEX_6 = 7'b0000010;		// six
parameter HEX_7 = 7'b1111000;		// seven
parameter HEX_8 = 7'b0000000;		// eight
parameter HEX_9 = 7'b0011000;		// nine
parameter HEX_10 = 7'b0001000;	// ten
parameter HEX_11 = 7'b0000011;	// eleven
parameter HEX_12 = 7'b1000110;	// twelve
parameter HEX_13 = 7'b0100001;	// thirteen
parameter HEX_14 = 7'b0000110;	// fourteen
parameter HEX_15 = 7'b0001110;	// fifteen
parameter OFF   = 7'b1111111;		// all off

logic [1:0] i_action, quantity;
logic rst_n, valid_i, valid_d, valid;
logic [PRICE_LEN-1:0] i_price, o_bid_best_price;
logic [QUANTITY_LEN-1 :0] i_quantity;
logic [TOT_QUATITY_LEN-1:0] o_bid_best_quant;
logic new_input_i, new_input_d, new_input;
logic i_side, side1, side2, side3, side4, side5;
logic [PRICE_LEN-1:0]price1, price2, price3, price4, price5;
logic [QUANTITY_LEN-1 :0] quant1, quant2, quant3, quant4, quant5;
logic [1:0] action1, action2, action3, action4, action5;
logic [ORDERID_LEN-1:0] i_order_id, order_id1, order_id2, order_id3, order_id4, order_id5;



assign rst_n = KEY[0];
assign valid_i = KEY[1];
assign new_input_i = KEY[2];
assign valid = valid_i && (!valid_d);
assign new_input = new_input_i && (!new_input_d);

always_ff @(posedge CLOCK_50, negedge rst_n) begin
	if(!rst_n) begin
		new_input_d <= 0;
		valid_d <= 0;
	end else begin
		new_input_d <= new_input_i;
		valid_d <= valid_i;
	end
end

always_ff @(posedge CLOCK_50, negedge rst_n) begin
	if(!rst_n) begin
		i_order_id <= '0;
		i_price <= '0;
		i_quantity <= '0;
		i_action <= '0;
		i_side <= 0;
		price1 <= 16'd400;
		price2 <= 16'd500;
		price3 <= 16'd400;
		price4 <= 16'd0;
		price5 <= 16'd600;
		quant1 <= 12'd10;
		quant2 <= 12'd40;
		quant3 <= 12'd5;
		quant4 <= 12'd0;
		quant5 <= 12'd100;
		side1 <= 0;
		side2 <= 0;
		side3 <= 0;
		side4 <= 0;
		side5 <= 0;
		action1 <= 2'b00;
		action2 <= 2'b00;
		action3 <= 2'b01;
		action4 <= 2'b11;
		action5 <= 2'b00;
		order_id1 <= 16'd1;
		order_id2 <= 16'd2;
		order_id3 <= 16'd1;
		order_id4 <= 16'd2;
		order_id5 <= 16'd3;
	end else if(new_input)begin
		i_order_id <= order_id1;
		order_id1 <= order_id2;
		order_id2 <= order_id3;
		order_id3 <= order_id4;
		order_id4 <= order_id5;
		i_price <= price1;
		price1 <= price2;
		price2 <= price3;
		price3 <= price4;
		price4 <= price5;
		i_quantity <= quant1;
		quant1 <= quant2;
		quant2 <= quant3;
		quant3 <= quant4;
		quant4 <= quant5;
		i_action <= action1;
		action1 <= action2;
		action2 <= action3;
		action3 <= action4;
		action4 <= action5;
		i_side <= side1;
		side1 <= side2;
		side2 <= side3;
		side3 <= side4;
		side4 <= side5;
	end
end


orderbook ob(
	.i_clk(CLOCK_50),
	.i_rst_n(rst_n),
	.i_order_id(i_order_id),
	.i_side(i_side),
	.i_price(i_price),
	.i_quantity(i_quantity),
	.i_action(i_action),
	.i_valid(valid),
	.o_bid_best_price(o_bid_best_price),
	.o_bid_best_quant(o_bid_best_quant),
	.o_ask_best_price(),
	.o_ask_best_quant(),
	.o_bid_best_valid(o_bid_best_valid),
	.o_ask_best_valid(),
	.o_action(),
	.o_price(),
	.o_quantity(),
	.o_valid()
);

always_comb begin
	if(o_bid_best_valid) begin
		case(o_bid_best_quant[3:0])
			4'd0: HEX0 = HEX_0;
			4'd1: HEX0 = HEX_1;
			4'd2: HEX0 = HEX_2;
			4'd3: HEX0 = HEX_3;
			4'd4: HEX0 = HEX_4;
			4'd5: HEX0 = HEX_5;
			4'd6: HEX0 = HEX_6;
			4'd7: HEX0 = HEX_7;
			4'd8: HEX0 = HEX_8;
			4'd9: HEX0 = HEX_9;
			4'd10: HEX0 = HEX_10;
			4'd11: HEX0 = HEX_11;
			4'd12: HEX0 = HEX_12;
			4'd13: HEX0 = HEX_13;
			4'd14: HEX0 = HEX_14;
			4'd15: HEX0 = HEX_15;
		endcase
	end else begin
		HEX0 = HEX_0;
	end
end

always_comb begin
	if(o_bid_best_valid) begin
		case(o_bid_best_quant[7:4])
			4'd0: HEX1 = HEX_0;
			4'd1: HEX1 = HEX_1;
			4'd2: HEX1 = HEX_2;
			4'd3: HEX1 = HEX_3;
			4'd4: HEX1 = HEX_4;
			4'd5: HEX1 = HEX_5;
			4'd6: HEX1 = HEX_6;
			4'd7: HEX1 = HEX_7;
			4'd8: HEX1 = HEX_8;
			4'd9: HEX1 = HEX_9;
			4'd10: HEX1 = HEX_10;
			4'd11: HEX1 = HEX_11;
			4'd12: HEX1 = HEX_12;
			4'd13: HEX1 = HEX_13;
			4'd14: HEX1 = HEX_14;
			4'd15: HEX1 = HEX_15;
		endcase
	end else begin
		HEX1 = HEX_0;
	end
end

always_comb begin
	if(o_bid_best_valid) begin
		case(o_bid_best_quant[11:8])
			4'd0: HEX2 = HEX_0;
			4'd1: HEX2 = HEX_1;
			4'd2: HEX2 = HEX_2;
			4'd3: HEX2 = HEX_3;
			4'd4: HEX2 = HEX_4;
			4'd5: HEX2 = HEX_5;
			4'd6: HEX2 = HEX_6;
			4'd7: HEX2 = HEX_7;
			4'd8: HEX2 = HEX_8;
			4'd9: HEX2 = HEX_9;
			4'd10: HEX2 = HEX_10;
			4'd11: HEX2 = HEX_11;
			4'd12: HEX2 = HEX_12;
			4'd13: HEX2 = HEX_13;
			4'd14: HEX2 = HEX_14;
			4'd15: HEX2 = HEX_15;
		endcase
	end else begin
		HEX2 = HEX_0;
	end
end

always_comb begin
	if(o_bid_best_valid) begin
		case(o_bid_best_price[3:0])
			4'd0: HEX3 = HEX_0;
			4'd1: HEX3 = HEX_1;
			4'd2: HEX3 = HEX_2;
			4'd3: HEX3 = HEX_3;
			4'd4: HEX3 = HEX_4;
			4'd5: HEX3 = HEX_5;
			4'd6: HEX3 = HEX_6;
			4'd7: HEX3 = HEX_7;
			4'd8: HEX3 = HEX_8;
			4'd9: HEX3 = HEX_9;
			4'd10: HEX3 = HEX_10;
			4'd11: HEX3 = HEX_11;
			4'd12: HEX3 = HEX_12;
			4'd13: HEX3 = HEX_13;
			4'd14: HEX3 = HEX_14;
			4'd15: HEX3 = HEX_15;
		endcase
	end else begin
		HEX3 = HEX_0;
	end
end

always_comb begin
	if(o_bid_best_valid) begin
		case(o_bid_best_price[7:4])
			4'd0: HEX4 = HEX_0;
			4'd1: HEX4 = HEX_1;
			4'd2: HEX4 = HEX_2;
			4'd3: HEX4 = HEX_3;
			4'd4: HEX4 = HEX_4;
			4'd5: HEX4 = HEX_5;
			4'd6: HEX4 = HEX_6;
			4'd7: HEX4 = HEX_7;
			4'd8: HEX4 = HEX_8;
			4'd9: HEX4 = HEX_9;
			4'd10: HEX4 = HEX_10;
			4'd11: HEX4 = HEX_11;
			4'd12: HEX4 = HEX_12;
			4'd13: HEX4 = HEX_13;
			4'd14: HEX4 = HEX_14;
			4'd15: HEX4 = HEX_15;
		endcase
	end else begin
		HEX4 = HEX_0;
	end
end
always_comb begin
	if(o_bid_best_valid) begin
		case(o_bid_best_price[11:8])
			4'd0: HEX5 = HEX_0;
			4'd1: HEX5 = HEX_1;
			4'd2: HEX5 = HEX_2;
			4'd3: HEX5 = HEX_3;
			4'd4: HEX5 = HEX_4;
			4'd5: HEX5 = HEX_5;
			4'd6: HEX5 = HEX_6;
			4'd7: HEX5 = HEX_7;
			4'd8: HEX5 = HEX_8;
			4'd9: HEX5 = HEX_9;
			4'd10: HEX5 = HEX_10;
			4'd11: HEX5 = HEX_11;
			4'd12: HEX5 = HEX_12;
			4'd13: HEX5 = HEX_13;
			4'd14: HEX5 = HEX_14;
			4'd15: HEX5 = HEX_15;
		endcase
	end else begin
		HEX5 = HEX_0;
	end
end



endmodule